# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2, 
# strandedness). Units are technical replicates (e.g. lanes, or resequencing of the 
# same biological sample).If the column "strandedness" is present (which is optional), 
# can be empty or has one of these values: none, yes or reverse. none is for unstranded 
# protocols, yes an reverse follow the nomenclature used in `htseq-count --reverse` 
# which is referenced in STAR manual section 7, "Counting number of reads per gene".

units: units.tsv

ref:
  # the star index location or genomefa to index
  index: "grch38_ens"
  genomefa: "/data/gpfs/assoc/inbre/projects/common_references/grch38_ens/Homo_sapiens.GRCh38.dna.primary_assembly.fa"
  transcriptomefa: "/data/gpfs/assoc/inbre/projects/common_references/grch38_ens/Homo_sapiens.GRCh38.cdna.all.fa"
  # gtf file with transcripts
  annotation: "/data/gpfs/assoc/inbre/projects/common_references/grch38_ens/Homo_sapiens.GRCh38.104.gtf"
  adapter: "/data/gpfs/assoc/inbre/projects/common_references/CustomBlacklist.fa"

params:
  trimmers: "fastp"
